

development:
  adapter: redis
  url: redis://redis:6379
  channel_prefix: streaming_logs_dev

test:
  adapter: async

production:
  adapter: redis
  url: redis://redis:6379
  channel_prefix: streaming_logs_production

