production:
  adapter: redis
  url: <%= ENV.fetch("REDISTOGO_URL") %>
  channel_prefix: deploy_app_to_heroku_production

development:
  adapter: redis
  url: redis://redis:6379/1

test:
  adapter: async
