development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  host: localhost
  pool: 5
  username: animagifadmin
  password: trytofindme288741

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  host: localhost
  pool: 5
  username: animagifadmin
  password: trytofindme288741

  production:
    adapter: postgresql
    encoding: unicode
    pool: 5
    url: <%= ENV["DATABASE_URL"] %>